server:
  port: 9090
spring:
  application:
    name: zuul
  profiles:
    active: prod
  devtools:
    add-properties: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

zuul:
  routes:
    authentication:
      path: '/authentication/**'
      url: "http://authentication:8080"
      sensitiveHeaders:

  prefix: '/services'

ribbon:
  eureka:
    enabled: false