server:
  port: 9090
spring:
  application:
    name: zuul
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignored-services: '*'