server:
  port: 9090
spring:
  application:
    name: zuul
  profiles:
    active: prod
  cloud:
    config:
      uri: http://config:8888
  devtools:
    add-properties: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

zuul:
  ignored-services: '*'
  routes:
    pgadmin:
      path: /pgadmin/**
      url: http://pgadmin/