app:
  jwtSecret: "!A%D*G-JaNdRgUkXp2s5v8y/B?E(H+MbPeShVmYq3t6w9z$C&F)J@NcRfTjWnZr4"
  jwtExpirationInMs: 604800000

database:
  url: postgresql://postgres/authentication
  username: authentication
  password: ZYcTCYwRLmYZ8y2h

service:
  account: http://account:8080
  authentication: http://authentication:8080
  transaction: http://transactions:8080
  exchange: http://exchange:3000