app:
  jwtSecret: "!A%D*G-JaNdRgUkXp2s5v8y/B?E(H+MbPeShVmYq3t6w9z$C&F)J@NcRfTjWnZr4"
  jwtExpirationInMs: 604800000

database:
  url: postgresql://postgres/transaction
  username: transaction
  password: AVc54VabhdP6uLnR