app:
  jwtSecret: "!A%D*G-JaNdRgUkXp2s5v8y/B?E(H+MbPeShVmYq3t6w9z$C&F)J@NcRfTjWnZr4"
  jwtExpirationInMs: 604800000

database:
  url: postgresql://postgres/transaction
  username: transaction
  password: AVc54VabhdP6uLnR

service:
  account: http://account:8080
  authentication: http://authentication:8080
  transaction: http://transaction:8080
  exchange: http://exchange:3000